/* Generates src/components/district48-cities.ts from Census TIGERweb
 * (generalized incorporated places + CDPs) clipped to the six district
 * counties. Run: npx tsx scripts/fetch-city-boundaries.mts */
import {writeFileSync} from 'node:fs'

import district48Data from '../src/components/indiana-district-map-coordinates'

type LonLat = [number, number]

const SERVICES = [
  'https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer',
  'https://tigerweb.geo.census.gov/arcgis/rest/services/Generalized_ACS2023/Places_CouSub_ConCity/MapServer',
]

const bbox = district48Data.district.bbox

function pointInRing(pt: LonLat, ring: LonLat[]): boolean {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]
    const [xj, yj] = ring[j]
    if (yi > pt[1] !== yj > pt[1] && pt[0] < ((xj - xi) * (pt[1] - yi)) / (yj - yi) + xi) {
      inside = !inside
    }
  }
  return inside
}

function countyFor(pt: LonLat): string | null {
  for (const county of district48Data.counties) {
    if (county.rings.some((r) => pointInRing(pt, r.coordinates as LonLat[]))) {
      return county.name
    }
  }
  return null
}

function centroidOf(rings: LonLat[][]): LonLat {
  let n = 0
  let sx = 0
  let sy = 0
  for (const ring of rings) {
    for (const [x, y] of ring) {
      sx += x
      sy += y
      n++
    }
  }
  return [sx / n, sy / n]
}

/* Full-fidelity rings: round to 5 decimals (~1 m) but never drop points.
 * Earlier point-capped versions made town borders visibly lumpy next to
 * the untrimmed township lines. */
function roundRing(ring: LonLat[]): LonLat[] {
  return ring.map(([x, y]): LonLat => [Number(x.toFixed(5)), Number(y.toFixed(5))])
}

async function fetchJson(url: string) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${res.status} ${url}`)
  return res.json()
}

async function main() {
  for (const service of SERVICES) {
    try {
      const meta = await fetchJson(`${service}?f=json`)
      const layers: Array<{id: number; name: string}> = meta.layers ?? []
      const targets = layers.filter((l) => /incorporated places$|census designated places$/i.test(l.name))
      if (targets.length === 0) continue
      const seen = new Set<string>()
      const cities: Array<{name: string; kind: string; county: string; pop: number; rings: LonLat[][]}> = []
      for (const layer of targets) {
        const envelope = `${bbox.minLon},${bbox.minLat},${bbox.maxLon},${bbox.maxLat}`
        const query =
          `${service}/${layer.id}/query?where=STATE%3D%2718%27&geometry=${envelope}` +
          `&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects` +
          `&outFields=BASENAME,POP100&returnGeometry=true&outSR=4326&f=geojson`
        let data = await fetchJson(query)
        if (data.error) {
          // Some layers (CDPs) reject POP100; retry with the bare field list.
          data = await fetchJson(query.replace('BASENAME,POP100', 'BASENAME'))
        }
        for (const feature of data.features ?? []) {
          const name = feature.properties?.BASENAME
          const pop = Number(feature.properties?.POP100 ?? 0) || 0
          const geom = feature.geometry
          if (!name || !geom) continue
          const polys: LonLat[][][] =
            geom.type === 'Polygon' ? [geom.coordinates] : geom.type === 'MultiPolygon' ? geom.coordinates : []
          const rings = polys.flat().map((r: LonLat[]) => roundRing(r))
          if (rings.length === 0) continue
          const county = countyFor(centroidOf(rings))
          if (!county) continue
          const key = `${name}|${county}`
          if (seen.has(key)) continue
          seen.add(key)
          cities.push({
            name,
            kind: /designated/i.test(layer.name) ? 'cdp' : 'town',
            county,
            pop,
            rings,
          })
        }
      }
      cities.sort((a, b) => a.county.localeCompare(b.county) || a.name.localeCompare(b.name))
      const header =
        `/* Generated by scripts/fetch-city-boundaries.mts on ${new Date().toISOString().slice(0, 10)}\n` +
        ` * Source: Census TIGERweb (${service.includes('Generalized') ? 'generalized' : 'full-res'} places), EPSG:4326.\n` +
        ` * Do not hand-edit; re-run the script instead. */\n\n` +
        `export type District48City = {\n  name: string\n  kind: 'town' | 'cdp'\n  county: string\n  pop: number\n  rings: Array<Array<[number, number]>>\n}\n\n`
      writeFileSync(
        'src/components/district48-cities.ts',
        `${header}export const district48Cities: District48City[] = ${JSON.stringify(cities, null, 1)}\n`
      )
      console.log(`Wrote ${cities.length} places from ${service}`)
      for (const c of cities) console.log(`  ${c.county}: ${c.name} (${c.kind}, ${c.rings.length} rings)`)
      return
    } catch (err) {
      console.error(`Service failed: ${service}`, err)
    }
  }
  throw new Error('All services failed')
}

main()
